/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimientocomputadores.interfaz;

import com.toedter.calendar.JCalendar;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mantenimientocomputadores.mundo.CaracteristicaFisica;
import mantenimientocomputadores.mundo.Computador;
import mantenimientocomputadores.mundo.Mantenimiento;
import mantenimientocomputadores.mundo.ProgramaInstalado;
import mantenimientocomputadores.mundo.SistemaPrincipal;

/**
 *
 * @author Luis Eduardo
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Completar
     */
    private Computador computador;
    
    private PanelPrincipal panelPrincipal;
    
    private DialogoPanelPrincipal dialogoPrincipal;
    /**
     * Completar
     */
    private SistemaPrincipalnterfaz principal;
    
    /**
     * Completar
     */
    DefaultTableModel tablaPc;
    
    /**
     * Completar
     */
    DefaultTableModel tablaCaracteristicaFisica;
    
    /**
     * Completar
     */
    DefaultTableModel tablaPrograma;
    
    /**
     * Completar
     */
    DefaultTableModel tablaMantenimiento; 
    
    /**
     * Completar
     */
    private SistemaPrincipal sistemaPrincipal;
    
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    /**
     * Creates new form PanelMantenimiento
     */
    public PanelPrincipal() {
        
        sistemaPrincipal = new SistemaPrincipal();
        initComponents();
       //Cargar el combo de computadores para las caracteristicas
        cargarListaComputadores();
        
        //Cargar el combo de caracteristicas
        cargarListaCategoriasCaracteristicas();
        
         //Cargar el combo de programas
        cargarListaCategoriasProgramas();
        
        //Creación de la tabla  computadores 
        tablaPc = new DefaultTableModel();
        tablaPc.addColumn("Código");
        tablaPc.addColumn("Precio");
        tablaPc.addColumn("Encargado");
        tablaPc.addColumn("Ubicación");
        this.tablaComputadores.setModel(tablaPc);
        
        //Creación de la tabla caracterisiticas
        tablaCaracteristicaFisica = new DefaultTableModel();
        tablaCaracteristicaFisica.addColumn("Código Pc");
        tablaCaracteristicaFisica.addColumn("Categoria");
        tablaCaracteristicaFisica.addColumn("Descripción");
        this.tablaCaracteristicas.setModel(tablaCaracteristicaFisica);
        
        //Creacion de la tabla programas instalados
        tablaPrograma = new DefaultTableModel();
        tablaPrograma.addColumn("Codigo Pc");
        tablaPrograma.addColumn("Categoria");
        tablaPrograma.addColumn("Descripción");
        this.tablaProgramas.setModel(tablaPrograma);
        
        //Creación de la tabla mantenimiento
        tablaMantenimiento = new DefaultTableModel();
        tablaMantenimiento.addColumn("Código Pc");
        tablaMantenimiento.addColumn("Fecha mantenimiento");
        tablaMantenimiento.addColumn("Encargado");
        tablaMantenimiento.addColumn("Descripción");
        this.tablaMantenimientos.setModel(tablaMantenimiento);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lb_codigo = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();
        lbl_encargado = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtEncargadoPC = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        lbl_ubicacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_AgregarComputador = new javax.swing.JButton();
        btn_ModificarComputador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComputadores = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_descripcionCaracteristica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboComputadoresCaracteristicas = new javax.swing.JComboBox<>();
        comboCategoriaCaracteristica = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btn_agregarCaracteristica = new javax.swing.JButton();
        btn_eliminarCaracteristica = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaCaracteristicas = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btn_ModificarCaracteristica = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_descripcionPrograma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboComputadoresProgramas = new javax.swing.JComboBox<>();
        comboCategoriaPrograma = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        btn_agregarPrograma = new javax.swing.JButton();
        btn_eliminarPrograma = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaProgramas = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        btn_modificarPrograma = new javax.swing.JButton();
        btn_cancelarPrograma = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtEncargado = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        comboComputadoresMantenimiento = new javax.swing.JComboBox<>();
        comboFecha = new com.toedter.calendar.JDateChooser();
        jPanel13 = new javax.swing.JPanel();
        btn_AgregarMantenimiento = new javax.swing.JButton();
        btn_ModificarMantenimiento = new javax.swing.JButton();
        btn_EliminarMantenimiento = new javax.swing.JButton();
        btn_CancelarMantenimiento = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaMantenimientos = new javax.swing.JTable();

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_codigo.setText("Còdigo:");

        lbl_precio.setText("Precio:");

        lbl_encargado.setText("Encargado:");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lbl_ubicacion.setText("Ubicaciòn:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_encargado)
                    .addComponent(lbl_precio)
                    .addComponent(lb_codigo)
                    .addComponent(lbl_ubicacion))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigo)
                    .addComponent(txtPrecio)
                    .addComponent(txtEncargadoPC)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_codigo))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_precio))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEncargadoPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_encargado))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ubicacion))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_AgregarComputador.setText("Agregar");
        btn_AgregarComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarComputadorActionPerformed(evt);
            }
        });

        btn_ModificarComputador.setText("Modificar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_AgregarComputador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btn_ModificarComputador)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AgregarComputador)
                    .addComponent(btn_ModificarComputador))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tablaComputadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Precio", "Encargado", "Ubicación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaComputadores);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Computador", jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Categoria:");

        jLabel6.setText("Descripción:");

        jLabel1.setText("Código PC:");

        comboComputadoresCaracteristicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboCategoriaCaracteristica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_descripcionCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboComputadoresCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategoriaCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboComputadoresCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCategoriaCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_descripcionCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_agregarCaracteristica.setText("Agregar");
        btn_agregarCaracteristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarCaracteristicaActionPerformed(evt);
            }
        });

        btn_eliminarCaracteristica.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btn_agregarCaracteristica)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarCaracteristica)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminarCaracteristica)
                    .addComponent(btn_agregarCaracteristica))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tablaCaracteristicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Categoria", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tablaCaracteristicas);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btn_ModificarCaracteristica.setText("Modificar");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btn_ModificarCaracteristica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_cancelar)
                .addGap(18, 18, 18))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ModificarCaracteristica)
                    .addComponent(btn_cancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Caracteristicas", jPanel5);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Categoria:");

        jLabel12.setText("Descripción:");

        jLabel2.setText("Código Pc:");

        comboComputadoresProgramas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboCategoriaPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCategoriaPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboComputadoresProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_descripcionPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboComputadoresProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboCategoriaPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_descripcionPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_agregarPrograma.setText("Agregar");
        btn_agregarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarProgramaActionPerformed(evt);
            }
        });

        btn_eliminarPrograma.setText("Eliminar");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_agregarPrograma)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarPrograma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminarPrograma)
                    .addComponent(btn_agregarPrograma))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tablaProgramas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Categoria", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tablaProgramas);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btn_modificarPrograma.setText("Modificar");
        btn_modificarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarProgramaActionPerformed(evt);
            }
        });

        btn_cancelarPrograma.setText("Cancelar");
        btn_cancelarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarProgramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_modificarPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(btn_cancelarPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificarPrograma)
                    .addComponent(btn_cancelarPrograma))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Programas", jPanel6);

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setText("Fecha mantenimiento :");

        jLabel18.setText("Encargado :");

        jLabel19.setText("Descripciòn :");

        jLabel20.setText("Código Pc:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane4.setViewportView(txtDescripcion);

        comboComputadoresMantenimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboComputadoresMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(comboComputadoresMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(34, 34, 34))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_AgregarMantenimiento.setText("Agregar");
        btn_AgregarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarMantenimientoActionPerformed(evt);
            }
        });

        btn_ModificarMantenimiento.setText("Modificar");

        btn_EliminarMantenimiento.setText("Eliminar");

        btn_CancelarMantenimiento.setText("Cancelar");
        btn_CancelarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarMantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btn_EliminarMantenimiento)
                        .addGap(61, 61, 61)
                        .addComponent(btn_CancelarMantenimiento))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btn_AgregarMantenimiento)
                        .addGap(61, 61, 61)
                        .addComponent(btn_ModificarMantenimiento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AgregarMantenimiento)
                    .addComponent(btn_ModificarMantenimiento))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_EliminarMantenimiento)
                    .addComponent(btn_CancelarMantenimiento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaMantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id computador", "Fecha mantenimiento", "Encargado", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tablaMantenimientos);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(148, 148, 148))
        );

        jTabbedPane6.addTab("Mantenimiento", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane6)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Completar
     * @param evt 
     */
    private void btn_cancelarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarProgramaActionPerformed
        // TODO add your handling code here:
        jTabbedPane6.setSelectedIndex(0);
    }//GEN-LAST:event_btn_cancelarProgramaActionPerformed

    /**
     * Completar
     * @param evt 
     */
    private void btn_modificarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarProgramaActionPerformed

    /**
     * Completar
     * @param evt 
     */
    private void btn_AgregarComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarComputadorActionPerformed
        // TODO add your handling code here:

        agregarComputador();
        
    }//GEN-LAST:event_btn_AgregarComputadorActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    /**
     * Completar
     * @param evt 
     */
    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:    
        jTabbedPane6.setSelectedIndex(0);
        
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * Completar
     * @param evt 
     */
    private void btn_agregarCaracteristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarCaracteristicaActionPerformed
        // TODO add your handling code here:
        try {
            agregarCaracteristica();    
            } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this,"Error: "+e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_agregarCaracteristicaActionPerformed

    /**
     * Completar
     * @param evt 
     */
    private void btn_agregarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarProgramaActionPerformed
        // TODO add your handling code here:
        try 
        {
            agregarProgramaInstalado();
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Error: "+ e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_agregarProgramaActionPerformed

    private void btn_AgregarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarMantenimientoActionPerformed
        try {
            // TODO add your handling code here:
            agregarMantenimiento();
        } catch (Exception ex) {
            Logger.getLogger(PanelPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error: "+ ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_AgregarMantenimientoActionPerformed

    private void btn_CancelarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarMantenimientoActionPerformed
        // TODO add your handling code here:
        jTabbedPane6.setSelectedIndex(0);
    }//GEN-LAST:event_btn_CancelarMantenimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AgregarComputador;
    private javax.swing.JButton btn_AgregarMantenimiento;
    private javax.swing.JButton btn_CancelarMantenimiento;
    private javax.swing.JButton btn_EliminarMantenimiento;
    private javax.swing.JButton btn_ModificarCaracteristica;
    private javax.swing.JButton btn_ModificarComputador;
    private javax.swing.JButton btn_ModificarMantenimiento;
    private javax.swing.JButton btn_agregarCaracteristica;
    private javax.swing.JButton btn_agregarPrograma;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelarPrograma;
    private javax.swing.JButton btn_eliminarCaracteristica;
    private javax.swing.JButton btn_eliminarPrograma;
    private javax.swing.JButton btn_modificarPrograma;
    private javax.swing.JComboBox<String> comboCategoriaCaracteristica;
    private javax.swing.JComboBox<String> comboCategoriaPrograma;
    private javax.swing.JComboBox<String> comboComputadoresCaracteristicas;
    private javax.swing.JComboBox<String> comboComputadoresMantenimiento;
    private javax.swing.JComboBox<String> comboComputadoresProgramas;
    private com.toedter.calendar.JDateChooser comboFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lbl_encargado;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_ubicacion;
    private javax.swing.JTable tablaCaracteristicas;
    private javax.swing.JTable tablaComputadores;
    private javax.swing.JTable tablaMantenimientos;
    private javax.swing.JTable tablaProgramas;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEncargado;
    private javax.swing.JTextField txtEncargadoPC;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txt_descripcionCaracteristica;
    private javax.swing.JTextField txt_descripcionPrograma;
    // End of variables declaration//GEN-END:variables

    //--------------------------------------------------------------------------
    // Metodos del panel principal de la interfaz
    //--------------------------------------------------------------------------
    /**
     * Completar
     */
    public void agregarComputador() {

        String[] datos = new String[4];
        datos[0] = txtCodigo.getText();
        txtCodigo.setText(null);
        datos[1] = txtPrecio.getText();
        txtPrecio.setText(null);
        datos[2] = txtEncargadoPC.getText();
        txtEncargadoPC.setText(null);
        datos[3] = txtUbicacion.getText();
        txtUbicacion.setText(null);

        try {
            if (datos[0].equals("") || datos[1].equals("") || datos[2].equals("") || datos[3].equals("")) {
                JOptionPane.showMessageDialog(this, "Todos los datos son requeridos", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                sistemaPrincipal.agregarComputador(Integer.parseInt(datos[0]), Integer.parseInt(datos[1]), datos[2], datos[3]);
                tablaPc.addRow(datos);
                cargarListaComputadores();
                JOptionPane.showMessageDialog(this, "Computador registrado satisfactoriamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            Logger.getLogger(PanelPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Completar
     */
    private void agregarCaracteristica() throws Exception {
        String[] caracteristicas = new String[3];
        if(comboComputadoresCaracteristicas.getItemCount() > 0)
        {
           caracteristicas[0]= comboComputadoresCaracteristicas.getSelectedItem().toString();
        }
        else
        {
            caracteristicas[0] = "";
        }
        caracteristicas[1] =comboCategoriaCaracteristica.getSelectedItem().toString();
        caracteristicas[2] = txt_descripcionCaracteristica.getText();
        txt_descripcionCaracteristica.setText("");
        
        
        if(caracteristicas[0].equals("") || caracteristicas[1].equals("") || caracteristicas[2].equals("")) 
        {
           JOptionPane.showMessageDialog(this, "Ingrese todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else
        {
            sistemaPrincipal.agregarCaracteristicafisica(Integer.parseInt(caracteristicas[0]),caracteristicas[1],caracteristicas[2]);
            tablaCaracteristicaFisica.addRow(caracteristicas);
            JOptionPane.showMessageDialog(this, "Caracteristica registrada satisfactoriamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        
       
    }
    
   /**
    * 
    * @throws Exception 
    */
    private void agregarProgramaInstalado() throws Exception
    {
        String[] programas = new String[3];
        
        if(comboComputadoresProgramas.getItemCount() > 0)
        {
           programas[0]= comboComputadoresProgramas.getSelectedItem().toString();
        }
        else
        {
           programas[0] = "";
        }
        programas[1] =comboCategoriaPrograma.getSelectedItem().toString();
        programas[2] = txt_descripcionPrograma.getText();
        txt_descripcionPrograma.setText("");
        
        
        if(programas[0].equals("") || programas[1].equals("") || programas[2].equals("")) 
        {
           JOptionPane.showMessageDialog(this, "Ingrese todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else
        {
            sistemaPrincipal.agregarProgramaInstalado(Integer.parseInt(programas[0]),programas[1],programas[2]);
            tablaPrograma.addRow(programas);
            JOptionPane.showMessageDialog(this, "Programa registrado satisfactoriamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }

    /**
     * Completar
     * @throws ParseException
     * @throws Exception 
     */
    private void agregarMantenimiento() throws Exception
    {
        
        //Mantenimiento mantenimientos= new Mantenimiento(Integer.parseInt(comboComputadoresMantenimiento.getSelectedItem().toString()), comboFecha.getDate(), txtEncargado.getText(), txtDescripcion.getText());
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaActual = new Date();
        String dateInString = "";
        boolean fechaValidada = false;
        if(comboFecha.getDate() != null)
        {
            dateInString = formatter.format(comboFecha.getDate());
            int comparacion = fechaActual.compareTo(comboFecha.getDate());
            if(comparacion >= 0)
            {
                fechaValidada = true;
            }
        }
        String[] mantenimiento =new String[4];
        
        if(comboComputadoresMantenimiento.getItemCount() > 0)
        {
           mantenimiento[0]= comboComputadoresMantenimiento.getSelectedItem().toString();
        }
        else
        {
           mantenimiento[0] = "";
        }
        
        mantenimiento[1]= dateInString;
        mantenimiento[2]= txtEncargado.getText();
        txtEncargado.setText("");
        mantenimiento[3]= txtDescripcion.getText();
        txtDescripcion.setText("");
        if(mantenimiento[0].equals("")|| mantenimiento[1].equals("") || mantenimiento[2].equals("")|| mantenimiento[3].equals(""))
        {
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(fechaValidada == false)
            {
                JOptionPane.showMessageDialog(this, "La fecha debe ser menor o igual a la fecha actual", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                sistemaPrincipal.agregarMantenimiento(Integer.parseInt(mantenimiento[0]),formatter.parse(mantenimiento[1]),mantenimiento[2],mantenimiento[3]);
                tablaMantenimiento.addRow(mantenimiento);
                JOptionPane.showMessageDialog(this, "Mantenimiento registrado satisfactoriamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    /**
     * Completar
     */
    private void cargarListaComputadores() 
    {
        ArrayList listaPC = new ArrayList<Computador>();
        listaPC = sistemaPrincipal.getComputadores();
        comboComputadoresCaracteristicas.removeAllItems();
        comboComputadoresProgramas.removeAllItems();
        comboComputadoresMantenimiento.removeAllItems();
        for (int i = 0; i < listaPC.size(); i++) {
            comboComputadoresCaracteristicas.addItem(listaPC.get(i).toString());
            comboComputadoresProgramas.addItem(listaPC.get(i).toString());
            comboComputadoresMantenimiento.addItem(listaPC.get(i).toString());
        }
    }
   
    
    /**
     * Completar
     */
    private void cargarListaCategoriasCaracteristicas() 
    {
        CaracteristicaFisica caracteristica = new CaracteristicaFisica(1,"","");
        comboCategoriaCaracteristica.removeAllItems();
        comboCategoriaCaracteristica.addItem(caracteristica.getCPU());
        comboCategoriaCaracteristica.addItem(caracteristica.getRAM());
        comboCategoriaCaracteristica.addItem(caracteristica.getDISCO_DURO());
        comboCategoriaCaracteristica.addItem(caracteristica.getTECLADO());
        comboCategoriaCaracteristica.addItem(caracteristica.getMOUSE());
        comboCategoriaCaracteristica.addItem(caracteristica.getUNIDAD_OPTICA());
    }
    
    /**
     * Completar
     */
    private void cargarListaCategoriasProgramas() 
    {
        ProgramaInstalado programa = new ProgramaInstalado(1,"","");
        comboCategoriaPrograma.removeAllItems();
        comboCategoriaPrograma.addItem(programa.getSISTEMA_OPERATIVO());
        comboCategoriaPrograma.addItem(programa.getOFIMATICA());
        comboCategoriaPrograma.addItem(programa.getGRAFICOS());
        comboCategoriaPrograma.addItem(programa.getANTIVIRUS());
        comboCategoriaPrograma.addItem(programa.getLENGUAJE_PROGRAMACION());
        comboCategoriaPrograma.addItem(programa.getIDE());
    }
}
